# Лабораторная работа №1
## Предобработка данных. Знакомство с pandas

Импортируем необходимые библиотеки:

In [45]:
import pandas as pd

Загружаем набор данных:

In [46]:
df = pd.read_csv("data/StudentsPerformance_lab.csv")

Выводим данные из датасета:

In [47]:
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72.0,74.0
1,female,group C,some college,standard,completed,69,90.0,88.0
2,female,group B,master's degree,standard,none,90,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,47,57.0,44.0
4,male,group C,some college,standard,none,76,78.0,75.0
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,NaN,95.0
996,male,group C,high school,free/reduced,none,62,55.0,55.0
997,female,group C,high school,free/reduced,completed,59,71.0,65.0
998,female,group D,NaN,standard,completed,68,NaN,NaN
999,female,group D,some college,free/reduced,none,77,86.0,86.0

Выводим количество пропусков в каждой колонке:

In [48]:
df.isna().sum()

gender                           0
race/ethnicity                   0
parental level of education    100
lunch                            0
test preparation course          0
math score                       0
reading score                  150
writing score                   90
dtype: int64

Видим, что значения пропущены в колонках **"parental level of education", "reading score", "writing score"**. Чтобы заполнить пропущенные значения, посчитаем среднее, медиану и моду:

In [49]:
reading_score_mean = df["reading score"].mean()
reading_score_mean

np.float64(69.57882352941176)

In [50]:
parental_level_mode = df["parental level of education"].mode()[0]
parental_level_mode

"associate's degree"

In [51]:
writing_score_median = df["writing score"].median()
writing_score_median

np.float64(69.0)

Заполняем пропуски посчитанными значениями:

In [52]:
df["reading score"] = df["reading score"].fillna(reading_score_mean)
df["parental level of education"] = df["parental level of education"].fillna(parental_level_mode)
df["writing score"] = df["writing score"].fillna(writing_score_median)

Проверяем, что пропусков действительно больше нет:

In [53]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Проведём нормализацию числовых данных:

In [54]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [55]:
df[['math score', 'reading score', 'writing score']] = scaler.fit_transform(df[['math score', 'reading score', 'writing score']])

Выберем колонки с категориальными признаками и произведём кодирование в численный вид:

In [56]:
cat_cols = df.select_dtypes(include=["str"]).columns
cat_cols

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='str')

In [57]:
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

Выведем конечный вид предобработанного датасета:

In [58]:
df

,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_standard,test preparation course_none
0,0.390024,1.818896e-01,0.395652,False,True,False,False,False,True,False,False,False,False,True,True
1,0.192076,1.534130e+00,1.370677,False,False,True,False,False,False,False,False,True,False,True,False
2,1.577711,1.909752e+00,1.718901,False,True,False,False,False,False,False,True,False,False,True,True
3,-1.259543,-9.449773e-01,-1.693689,True,False,False,False,False,False,False,False,False,False,False,True
4,0.653954,6.326363e-01,0.465296,True,False,True,False,False,False,False,False,True,False,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,1.445746,-1.067583e-15,1.858190,False,False,False,False,True,False,False,True,False,False,True,False
996,-0.269803,-1.095226e+00,-0.927598,True,False,True,False,False,False,True,False,False,False,False,True
997,-0.467751,1.067651e-01,-0.231151,False,False,True,False,False,False,True,False,False,False,False,False
998,0.126093,-1.067583e-15,0.047428,False,False,False,True,False,False,False,False,False,False,True,False
999,0.719937,1.233632e+00,1.231388,False,False,False,True,False,False,False,False,True,False,False,True

Сохраним датасет:

In [59]:
df.to_csv("data/StudentsPerformance_processed.csv")