# Лабораторная работа №1
## Предобработка данных. Знакомство с pandas

Импортируем необходимые библиотеки:

In [62]:
import pandas as pd

Загружаем набор данных:

In [63]:
df = pd.read_csv("data/bigmart_data_lab.csv")

Выводим данные из датасета:

In [64]:
df

,Item_Identifier,Item_Weight,Item_Fat_Content,Item_Visibility,Item_Type,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Outlet_Size,Outlet_Location_Type,Outlet_Type,Item_Outlet_Sales
0,FDA15,9.300,Low Fat,0.016047,Dairy,249.8092,OUT049,1999,Medium,Tier 1,Supermarket Type1,3735.1380
1,DRC01,5.920,Regular,0.019278,Soft Drinks,48.2692,OUT018,2009,Medium,Tier 3,Supermarket Type2,443.4228
2,FDN15,17.500,Low Fat,0.016760,Meat,141.6180,OUT049,1999,Medium,Tier 1,Supermarket Type1,2097.2700
3,FDX07,19.200,Regular,0.000000,Fruits and Vegetables,182.0950,OUT010,1998,NaN,Tier 3,Grocery Store,732.3800
4,NCD19,8.930,Low Fat,0.000000,Household,53.8614,OUT013,1987,High,Tier 3,Supermarket Type1,994.7052
...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,6.865,Low Fat,0.056783,Snack Foods,214.5218,OUT013,1987,High,Tier 3,Supermarket Type1,2778.3834
8519,FDS36,8.380,Regular,0.046982,Baking Goods,NaN,OUT045,2002,NaN,Tier 2,Supermarket Type1,549.2850
8520,NCJ29,10.600,Low Fat,0.035186,Health and Hygiene,85.1224,OUT035,2004,Small,Tier 2,Supermarket Type1,1193.1136
8521,FDN46,7.210,Regular,0.145221,Snack Foods,NaN,OUT018,2009,Medium,Tier 3,Supermarket Type2,1845.5976
8522,DRG01,14.800,Low Fat,0.044878,Soft Drinks,75.4670,OUT046,1997,Small,Tier 1,Supermarket Type1,765.6700

Выводим количество пропусков в каждой колонке:

In [65]:
df.isna().sum()

Item_Identifier                 0
Item_Weight                  1463
Item_Fat_Content                0
Item_Visibility                 0
Item_Type                     852
Item_MRP                     1705
Outlet_Identifier               0
Outlet_Establishment_Year       0
Outlet_Size                  2410
Outlet_Location_Type            0
Outlet_Type                     0
Item_Outlet_Sales               0
dtype: int64

Видим, что значения пропущены в колонках **Item_Weight, Item_Type, Item_MRP, Outlet_Size**. Чтобы заполнить пропущенные значения, посчитаем среднее, медиану и моду:

In [66]:
item_weight_mean = df["Item_Weight"].mean()
item_weight_mean

np.float64(12.857645184135977)

In [67]:
outlet_size_mode = df["Outlet_Size"].mode()[0]
outlet_size_mode

'Medium'

In [68]:
item_type_mode = df["Item_Type"].mode()[0]
item_type_mode

'Fruits and Vegetables'

In [69]:
item_mrp_median = df["Item_MRP"].median()
item_mrp_median

np.float64(144.26280000000003)

Заполняем пропуски посчитанными значениями:

In [70]:
df["Item_Weight"] = df["Item_Weight"].fillna(item_weight_mean)
df["Outlet_Size"] = df["Outlet_Size"].fillna(outlet_size_mode)
df["Item_Type"] = df["Item_Type"].fillna(item_type_mode)
df["Item_MRP"] = df["Item_MRP"].fillna(item_mrp_median)

Проверяем, что пропусков действительно больше нет:

In [71]:
df.isna().sum()

Item_Identifier              0
Item_Weight                  0
Item_Fat_Content             0
Item_Visibility              0
Item_Type                    0
Item_MRP                     0
Outlet_Identifier            0
Outlet_Establishment_Year    0
Outlet_Size                  0
Outlet_Location_Type         0
Outlet_Type                  0
Item_Outlet_Sales            0
dtype: int64

Проведём нормализацию числовых данных:

In [72]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [73]:
df[['Item_Weight', 'Item_MRP', 'Item_Visibility']] = scaler.fit_transform(df[['Item_Weight', 'Item_MRP', 'Item_Visibility']])

In [74]:
df.nunique()

Item_Identifier              1559
Item_Weight                   416
Item_Fat_Content                5
Item_Visibility              7880
Item_Type                      16
Item_MRP                     5089
Outlet_Identifier              10
Outlet_Establishment_Year       9
Outlet_Size                     3
Outlet_Location_Type            3
Outlet_Type                     4
Item_Outlet_Sales            3493
dtype: int64

Выберем колонки с категориальными признаками и произведём кодирование в численный вид:

In [75]:
cat_cols = ["Item_Type", "Item_Fat_Content", "Outlet_Size", "Outlet_Location_Type", "Outlet_Type"]
cat_cols

['Item_Type',
 'Item_Fat_Content',
 'Outlet_Size',
 'Outlet_Location_Type',
 'Outlet_Type']

In [76]:
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

Выведем конечный вид предобработанного датасета:

In [77]:
df

,Item_Identifier,Item_Weight,Item_Visibility,Item_MRP,Outlet_Identifier,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,...,Item_Fat_Content_Regular,Item_Fat_Content_low fat,Item_Fat_Content_reg,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,FDA15,-0.841872,-0.970732,1.920266,OUT049,1999,3735.1380,False,False,False,...,False,False,False,True,False,False,False,True,False,False
1,DRC01,-1.641706,-0.908111,-1.682095,OUT018,2009,443.4228,False,False,False,...,True,False,False,True,False,False,True,False,True,False
2,FDN15,1.098554,-0.956917,-0.013563,OUT049,1999,2097.2700,False,False,False,...,False,False,False,True,False,False,False,True,False,False
3,FDX07,1.500838,-1.281758,0.709930,OUT010,1998,732.3800,False,False,False,...,True,False,False,True,False,False,True,False,False,False
4,NCD19,-0.929428,-1.281758,-1.582139,OUT013,1987,994.7052,False,False,False,...,False,False,False,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,FDF22,-1.418084,-0.181193,1.289532,OUT013,1987,2778.3834,False,False,False,...,False,False,False,False,False,False,True,True,False,False
8519,FDS36,-1.059578,-0.371154,0.033711,OUT045,2002,549.2850,False,False,False,...,True,False,False,True,False,True,False,True,False,False
8520,NCJ29,-0.534243,-0.599784,-1.023375,OUT035,2004,1193.1136,False,False,False,...,False,False,False,False,True,True,False,True,False,False
8521,FDN46,-1.336444,1.532880,0.033711,OUT018,2009,1845.5976,False,False,False,...,True,False,False,True,False,False,True,False,True,False
8522,DRG01,0.459634,-0.411936,-1.195957,OUT046,1997,765.6700,False,False,False,...,False,False,False,False,True,False,False,True,False,False

In [78]:
df.drop(columns=["Item_Identifier", "Outlet_Identifier"], inplace=True)
df

,Item_Weight,Item_Visibility,Item_MRP,Outlet_Establishment_Year,Item_Outlet_Sales,Item_Type_Breads,Item_Type_Breakfast,Item_Type_Canned,Item_Type_Dairy,Item_Type_Frozen Foods,...,Item_Fat_Content_Regular,Item_Fat_Content_low fat,Item_Fat_Content_reg,Outlet_Size_Medium,Outlet_Size_Small,Outlet_Location_Type_Tier 2,Outlet_Location_Type_Tier 3,Outlet_Type_Supermarket Type1,Outlet_Type_Supermarket Type2,Outlet_Type_Supermarket Type3
0,-0.841872,-0.970732,1.920266,1999,3735.1380,False,False,False,True,False,...,False,False,False,True,False,False,False,True,False,False
1,-1.641706,-0.908111,-1.682095,2009,443.4228,False,False,False,False,False,...,True,False,False,True,False,False,True,False,True,False
2,1.098554,-0.956917,-0.013563,1999,2097.2700,False,False,False,False,False,...,False,False,False,True,False,False,False,True,False,False
3,1.500838,-1.281758,0.709930,1998,732.3800,False,False,False,False,False,...,True,False,False,True,False,False,True,False,False,False
4,-0.929428,-1.281758,-1.582139,1987,994.7052,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8518,-1.418084,-0.181193,1.289532,1987,2778.3834,False,False,False,False,False,...,False,False,False,False,False,False,True,True,False,False
8519,-1.059578,-0.371154,0.033711,2002,549.2850,False,False,False,False,False,...,True,False,False,True,False,True,False,True,False,False
8520,-0.534243,-0.599784,-1.023375,2004,1193.1136,False,False,False,False,False,...,False,False,False,False,True,True,False,True,False,False
8521,-1.336444,1.532880,0.033711,2009,1845.5976,False,False,False,False,False,...,True,False,False,True,False,False,True,False,True,False
8522,0.459634,-0.411936,-1.195957,1997,765.6700,False,False,False,False,False,...,False,False,False,False,True,False,False,True,False,False

Сохраним датасет:

In [79]:
df.to_csv("data/bigmart_data_processed.csv")