# Лабораторная работа №1
## Предобработка данных. Знакомство с pandas

Импортируем библиотеку:

In [9]:
import pandas as pd

Загружаем набор данных:

In [10]:
df = pd.read_csv("data/StudentsPerformance_lab.csv")

Выводим данные из датасета:

In [11]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72.0,74.0
1,female,group C,some college,standard,completed,69,90.0,88.0
2,female,group B,master's degree,standard,none,90,95.0,93.0
3,male,group A,associate's degree,free/reduced,none,47,57.0,44.0
4,male,group C,some college,standard,none,76,78.0,75.0

Посмотрим общую информацию о данных в датасете:

In [12]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  900 non-null    str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                850 non-null    float64
 7   writing score                910 non-null    float64
dtypes: float64(2), int64(1), str(5)
memory usage: 102.2 KB

Выведем описательные статистики численных признаков:

In [13]:
df.describe()

       math score  reading score  writing score
count  1000.00000     850.000000     910.000000
mean     66.08900      69.578824      68.251648
std      15.16308      14.446572      15.058499
min       0.00000      24.000000      15.000000
25%      57.00000      60.000000      58.000000
50%      66.00000      70.000000      69.000000
75%      77.00000      80.000000      79.000000
max     100.00000     100.000000     100.000000

Выводим количество пропусков в каждой колонке:

In [14]:
df.isna().sum()

gender                           0
race/ethnicity                   0
parental level of education    100
lunch                            0
test preparation course          0
math score                       0
reading score                  150
writing score                   90
dtype: int64

Видим, что значения пропущены в колонках **"parental level of education", "reading score", "writing score"**. Чтобы заполнить пропущенные значения, посчитаем среднее, медиану и моду:

In [15]:
reading_score_mean = df["reading score"].mean()
reading_score_mean

np.float64(69.57882352941176)

In [16]:
parental_level_mode = df["parental level of education"].mode()[0]
parental_level_mode

"associate's degree"

In [17]:
writing_score_median = df["writing score"].median()
writing_score_median

np.float64(69.0)

Заполняем пропуски посчитанными значениями:

In [18]:
df["reading score"] = df["reading score"].fillna(reading_score_mean)
df["parental level of education"] = df["parental level of education"].fillna(parental_level_mode)
df["writing score"] = df["writing score"].fillna(writing_score_median)

Проверяем, что пропусков действительно больше нет:

In [19]:
df.isna().sum()

gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

Проведём нормализацию числовых данных:

In [20]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

In [21]:
df[['reading score', 'writing score']] = scaler.fit_transform(df[['reading score', 'writing score']])

Выберем колонки с категориальными признаками и произведём кодирование в численный вид:

In [22]:
cat_cols = df.select_dtypes(include=["str"]).columns
cat_cols

Index(['gender', 'race/ethnicity', 'parental level of education', 'lunch',
       'test preparation course'],
      dtype='str')

In [23]:
df = pd.get_dummies(df, columns=cat_cols, drop_first=True)

Выведем конечный вид предобработанного датасета:

In [24]:
df.head()

,math score,reading score,writing score,gender_male,race/ethnicity_group B,race/ethnicity_group C,race/ethnicity_group D,race/ethnicity_group E,parental level of education_bachelor's degree,parental level of education_high school,parental level of education_master's degree,parental level of education_some college,parental level of education_some high school,lunch_standard,test preparation course_none
0,72,0.181890,0.395652,False,True,False,False,False,True,False,False,False,False,True,True
1,69,1.534130,1.370677,False,False,True,False,False,False,False,False,True,False,True,False
2,90,1.909752,1.718901,False,True,False,False,False,False,False,True,False,False,True,True
3,47,-0.944977,-1.693689,True,False,False,False,False,False,False,False,False,False,False,True
4,76,0.632636,0.465296,True,False,True,False,False,False,False,False,True,False,True,True

Сохраним датасет:

In [15]:
df.to_csv("data/StudentsPerformance_processed.csv")